export const STUDY_PLAN = {
  'toeic-0-300': {
    title: 'Lộ trình học TOEIC NỀN TẢNG (0–300)',
    description: 'Kế hoạch 35 ngày giúp bạn nắm vững nền tảng ngữ pháp, từ vựng và tự tin bước vào kỳ thi.',
    plans: [
      { day: 'Day 1', newLesson: 'Giới thiệu chung về bài thi và phương pháp học', review: null },
      { day: 'Day 2', newLesson: 'Danh từ', review: null },
      { day: 'Day 3', newLesson: 'Mini test 1', review: null },
      { day: 'Day 4', newLesson: 'Động từ', review: null },
      { day: 'Day 5', newLesson: 'Mini test 2', review: null },
      {
        day: 'Day 6',
        newLesson: 'Đại từ',
        review: 'Ôn lại bài Danh từ (Section 1 + 2): các loại danh từ; danh từ đếm được và danh từ không đếm được',
      },
      {
        day: 'Day 7',
        newLesson: 'Mini test 3',
        review:
          'Mini test 1; Động từ (Section 1 + 2 + 3): các loại động từ, thì hiện tại đơn và thì hiện tại tiếp diễn',
      },
      { day: 'Day 8', newLesson: 'Tính từ và Trạng từ', review: 'Mini test 2' },
      {
        day: 'Day 9',
        newLesson: 'Giới từ',
        review: 'Đại từ (Section 1 + 2): Đại từ nhân xưng, tính từ sở hữu và đại từ sở hữu; Mini test 3',
      },
      {
        day: 'Day 10',
        newLesson: 'Mini test 4',
        review:
          'Tính từ (Section 1 + 2): Tính từ, thứ tự tính từ; Danh từ (Section 3 + 4): Sở hữu cách, Hạn định từ; Mini test 1',
      },
      {
        day: 'Day 11',
        newLesson: 'Các mẫu câu',
        review:
          'Động từ (Section 4 + 5 + 6): Quá khứ đơn, tương lai đơn, danh động từ và động từ nguyên thể; Đại từ (Section 3): Đại từ phản thân; Mini test 2',
      },
      {
        day: 'Day 12',
        newLesson: 'Trạng từ (Section 3, 4 và 5): Trạng từ, vị trí của trạng từ, sự khác biệt giữa tính từ và trạng từ',
        review: 'Mini test 3',
      },
      { day: 'Day 13', newLesson: 'Giới từ (Chỉ địa điểm và chỉ thời gian)', review: null },
      { day: 'Day 14', newLesson: 'Các mẫu câu', review: 'Mini test 4' },
      { day: 'Day 15', newLesson: 'NGHỈ NGƠI', review: null },
      { day: 'Day 16', newLesson: 'Lesson 1 (Khóa từ vựng cơ bản)', review: null },
      { day: 'Day 17', newLesson: 'Từ vựng về chủ đề Thế giới tự nhiên', review: null },
      { day: 'Day 18', newLesson: 'Mini-test 1', review: null },
      { day: 'Day 19', newLesson: 'Từ vựng về chủ đề Hoạt động hàng ngày', review: null },
      { day: 'Day 20', newLesson: 'Từ vựng về chủ đề Gia đình', review: null },
      { day: 'Day 21', newLesson: 'Mini-test 2', review: null },
      { day: 'Day 22', newLesson: 'Từ vựng về chủ đề Kiến trúc và nội thất', review: 'Mở đầu; Thế giới tự nhiên' },
      { day: 'Day 23', newLesson: 'Từ vựng về chủ đề Sức khỏe', review: 'Mini-test 1' },
      { day: 'Day 24', newLesson: 'Mini-test 3', review: 'Từ vựng về chủ đề Hoạt động hàng ngày' },
      {
        day: 'Day 25',
        newLesson: 'Từ vựng về chủ đề Đời sống sinh viên',
        review: 'Từ vựng về chủ đề Gia đình; Mini-test 2',
      },
      {
        day: 'Day 26',
        newLesson: 'Từ vựng về chủ đề Thời gian rảnh rỗi',
        review: 'Từ vựng về chủ đề Kiến trúc và nội thất',
      },
      { day: 'Day 27', newLesson: 'Mini-test 4', review: 'Mở đầu; Sức khỏe; Mini-test 3' },
      {
        day: 'Day 28',
        newLesson: 'Từ vựng về chủ đề Công việc và đồng nghiệp',
        review: 'Từ vựng về chủ đề: Đời sống sinh viên; Thế giới tự nhiên; Mini-test 1',
      },
      {
        day: 'Day 29',
        newLesson: 'Từ vựng về chủ đề Công nghệ',
        review: 'Từ vựng về chủ đề: Thời gian rảnh rỗi; Hoạt động hàng ngày; Gia đình; Mini-test 2; Mini-test 4',
      },
      {
        day: 'Day 30',
        newLesson: 'Mini test 5',
        review: 'Từ vựng về chủ đề: Công việc và đồng nghiệp; Kiến trúc và nội thất; Sức khỏe',
      },
      {
        day: 'Day 31',
        newLesson: 'Từ vựng về chủ đề Email',
        review: 'Từ vựng về chủ đề: Công nghệ, Đời sống sinh viên và Thời gian rảnh rỗi; Mini-test 3',
      },
      {
        day: 'Day 32',
        newLesson: 'Từ vựng về chủ đề Telephone',
        review: 'Mini-test 4 và 5; Từ vựng về chủ đề: Công việc và đồng nghiệp; Email',
      },
      {
        day: 'Day 33',
        newLesson: 'Final test',
        review: 'Từ vựng về chủ đề: Telephone, Công nghệ và Email; Mini test 5',
      },
      { day: 'Day 34', newLesson: 'Từ vựng về chủ đề Telephone', review: 'Final test' },
      { day: 'Day 35', newLesson: 'NGHỈ NGƠI', review: null },
    ],
  },
  'toeic-300-600': {
    title: 'Lộ trình học TOEIC TRUNG CẤP (300–600)',
    description: 'Kế hoạch 49 ngày tập trung vào Listening Part 1-2, Reading Part 5-6 và Từ vựng theo chủ đề nâng cao.',
    plans: [
      { day: 'Day 1', newLesson: 'Giới thiệu chung về bài thi và phương pháp học', review: null },
      { day: 'Day 2', newLesson: 'Lesson 2: Listening Part 1-Tranh tả người', review: null },
      { day: 'Day 3', newLesson: 'Lesson 1: Giới thiệu khóa học - Contracts và Marketing', review: null },
      { day: 'Day 4', newLesson: 'Lesson 3: Giới thiệu chung về Reading Part 5 + Cách làm bài', review: null },
      { day: 'Day 5', newLesson: 'Lesson 2: Warranties và Business Planning', review: null },
      {
        day: 'Day 6',
        newLesson: 'Lesson 4: Listening Part 2 - Giới thiệu về câu hỏi WH và dạng câu hỏi How',
        review: null,
      },
      { day: 'Day 7', newLesson: 'Lesson 3 - Conference và Computers', review: null },
      { day: 'Day 8', newLesson: 'Lesson 5: Reading Part 5-Danh từ', review: null },
      { day: 'Day 9', newLesson: 'Lesson 4: Office technology và Office Procedures', review: null },
      { day: 'Day 10', newLesson: 'Lesson 6: Listening Part 1-Tranh tả vật', review: null },
      {
        day: 'Day 11',
        newLesson: 'Lesson 5: Electronics và Correspondence',
        review: 'Lesson 1 - Giới thiệu khóa học - Contracts và Marketing (Khóa từ vựng)',
      },
      { day: 'Day 12', newLesson: 'Lesson 7: Reading Part 5-5 - Đại từ', review: null },
      { day: 'Day 13', newLesson: 'Mini test 1', review: null },
      {
        day: 'Day 14',
        newLesson: 'Lesson 8: Listening Part 2 - 7 dạng câu hỏi What trong phần Listening',
        review: 'Lesson 2: Warranties và Business Planning',
      },
      { day: 'Day 15', newLesson: 'Lesson 6: Job advertising & Recruiting và Applying and interviewing', review: null },
      {
        day: 'Day 16',
        newLesson: 'Lesson 9: Reading Part 5 - Tính từ',
        review: 'Lesson 3: Conference và Computers; Lesson 4: Office technology và Office Procedures',
      },
      { day: 'Day 17', newLesson: 'Lesson 7: Hiring and Training và Salaries & benefits', review: null },
      {
        day: 'Day 18',
        newLesson: 'Lesson 10: Listening Part 1 - ôn tập',
        review: 'Lesson 1: Contracts và Marketing; Lesson 5: Electronics và Correspondence',
      },
      {
        day: 'Day 19',
        newLesson: 'Lesson 8: Promotions, Pensions, Awards và Shopping',
        review:
          'Lesson 2: Warranties và Business Planning; Lesson 6: Job advertising & Recruiting và Applying and interviewing',
      },
      { day: 'Day 20', newLesson: 'Lesson 11: Reading Part 5 - Trạng từ', review: null },
      {
        day: 'Day 21',
        newLesson: 'Lesson 9: Ordering Supplies và Shipping',
        review: 'Lesson 3 - Conference và Computers; Lesson 7: Hiring and Training và Salaries & benefits',
      },
      {
        day: 'Day 22',
        newLesson: 'Lesson 12: Listening Part 2-Câu hỏi Why & câu hỏi Lựa chọn',
        review: 'Lesson 2: Listening Part 1 - Tranh tả người',
      },
      {
        day: 'Day 23',
        newLesson: 'Lesson 10: Invoices và Inventory',
        review: 'Lesson 4: Office technology và Office Procedures; Lesson 5: Electronics và Correspondence',
      },
      {
        day: 'Day 24',
        newLesson: 'Kiểm tra giữa kì (gồm 3 phần: Part 1 & Part 2 Listening - Part 5 Reading)',
        review: 'Lesson 3 + 4 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 25',
        newLesson: 'Mini test 2 (Vocab)',
        review:
          'Lesson 6: Job advertising & Recruiting và Applying and interviewing; Lesson 8: Promotions, Pensions, Awards và Shopping',
      },
      {
        day: 'Day 26',
        newLesson: 'Lesson 13: Reading Part 6 - Giới thiệu chung và cách làm bài',
        review: 'Lesson 5: Reading Part 5 - Danh từ',
      },
      {
        day: 'Day 27',
        newLesson: 'Lesson 7: Hiring and Training và Salaries & benefits',
        review: 'Lesson 9: Ordering Supplies và Shipping',
      },
      {
        day: 'Day 28',
        newLesson:
          'Lesson 14: Listening Part 2 - Câu hỏi Yes/No và các mẹo trả lời câu hỏi Listening Part 2 Tips in part 2',
        review: 'Lesson 6 + 7 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 29',
        newLesson: 'Lesson 8: Promotions, Pensions, Awards và Shopping',
        review: 'Lesson 15 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 30',
        newLesson: 'Lesson 15: Reading Part 6 - Hòa hợp S +V',
        review: 'Lesson 2, 3, 16 và 17 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 31',
        newLesson: 'Lesson 10: Invoices và Inventory',
        review: 'Lesson 4, 5, 6 và 18 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 32',
        newLesson: 'Lesson 16: Giới thiệu về Listening Part 3',
        review: 'Lesson 7, 8 và Lesson 19 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 33',
        newLesson: 'Lesson 17: Reading Part 6 - Câu bị động',
        review: 'Lesson 9, 10, 11, và 20 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 34',
        newLesson: 'Lesson 18: Listening Part 3 - Câu hỏi về nội dung',
        review: 'Lesson 12, 13, 21 và 22 (Khóa TOEIC 300-600+)',
      },
      { day: 'Day 35', newLesson: 'Lesson 19: Reading Part 6-Liên từ', review: 'NGHỈ NGƠI' },
      {
        day: 'Day 36',
        newLesson: 'Lesson 20: Listening part 3 - Câu hỏi trích dẫn',
        review: 'Lesson 15 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 37',
        newLesson: 'Lesson 21: Reading Part 6 - Mệnh đề quan hệ',
        review: 'Lesson 2, 3, 16 và 17 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 38',
        newLesson: 'Lesson 22: Giới thiệu về Listening Part 4',
        review: 'Lesson 4, 5, 6 và 18 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 39',
        newLesson: 'Lesson 23: Giới thiệu về Reading P7',
        review: 'Lesson 7, 8 và Lesson 19 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 40',
        newLesson: 'Lesson 24: Listening Part 4 - Câu hỏi bảng biểu',
        review: 'Lesson 9, 10, 11, và 20 (Khóa TOEIC 300-600+)',
      },
      {
        day: 'Day 41',
        newLesson: 'Lesson 25: Reading Part 7 - Kĩ năng Scanning',
        review: 'Lesson 12, 13, 21 và 22 (Khóa TOEIC 300-600+)',
      },
      { day: 'Day 42', newLesson: 'Kiểm tra cuối khóa', review: 'NGHỈ NGƠI' },
      { day: 'Day 43', newLesson: null, review: 'Lesson 14, 15, 16, và 23 (Khóa TOEIC 300-600+)' },
      { day: 'Day 44', newLesson: null, review: 'Lesson 17, 18, 24 và 25 (Khóa TOEIC 300-600+)' },
      { day: 'Day 45', newLesson: null, review: 'Lesson 19 + 20 + 21 (Khóa TOEIC 300-600+)' },
      { day: 'Day 46', newLesson: null, review: 'Lesson 22 + 23 (Khóa TOEIC 300-600+)' },
      { day: 'Day 47', newLesson: null, review: 'Lesson 24 + 25 (Khóa TOEIC 300-600+)' },
      { day: 'Day 48', newLesson: 'NGHỈ NGƠI', review: null },
      { day: 'Day 49', newLesson: 'NGHỈ NGƠI', review: null },
    ],
  },
  'toeic-600-800': {
    title: 'Lộ trình học TOEIC CHUYÊN SÂU (600–800+)',
    description:
      'Kế hoạch 60 ngày đi sâu vào các mẹo nâng cao, từ vựng chuyên ngành và các bẫy thường gặp trong bài thi.',
    plans: [
      { day: 'Day 1', newLesson: 'Giới thiệu chung về bài thi và phương pháp học', review: null },
      {
        day: 'Day 2',
        newLesson: 'Lesson 2: Investments và Taxes; Lesson 2: Listening Part 1-Chủ đề Workplace',
        review: null,
      },
      {
        day: 'Day 3',
        newLesson: 'Lesson 3: Reading Part 5 và 6 - Mẹo ngữ pháp nâng cao tổng hợp',
        review: 'Lesson 1: Banking and Accounting',
      },
      { day: 'Day 4', newLesson: 'Lesson 4: Listening Part 2 - Câu hỏi who, where và when', review: null },
      {
        day: 'Day 5',
        newLesson:
          'Lesson 5: Product development và Renting & Leasing; Lesson 5: Reading Part 7 - Kĩ năng Skimming và Scanning',
        review: null,
      },
      { day: 'Day 6', newLesson: 'Lesson 6: Listening part 3 - Kiểm soát thời gian', review: null },
      { day: 'Day 7', newLesson: 'Lesson 7: Reading Part 5 và 6 - Vị trí trạng từ', review: null },
      { day: 'Day 8', newLesson: 'Lesson 4: Board meetings & Committees và Quality control', review: null },
      { day: 'Day 9', newLesson: 'Lesson 5: Product development và Renting & Leasing', review: null },
      { day: 'Day 10', newLesson: null, review: null },
      { day: 'Day 11', newLesson: null, review: null },
      { day: 'Day 12', newLesson: 'Lesson 5: Product development và Renting & Leasing', review: null },
      { day: 'Day 13', newLesson: 'Lesson 7: Reading Part 5 và 6 - Vị trí trạng từ', review: null },
      { day: 'Day 14', newLesson: 'Mini test 1 (Khóa TOEIC 600-800+)', review: null },
      { day: 'Day 15', newLesson: 'Lesson 8: Listening Part 4-Office talks', review: 'Ôn lại Lesson 3 (Khóa từ vựng)' },
      { day: 'Day 16', newLesson: 'Lesson 6: Selecting a Restaurant và Eating out', review: null },
      {
        day: 'Day 17',
        newLesson: 'Lesson 9: Listening Part 1 và 2 - Các bẫy thường gặp của Part 1 + câu hỏi Why của Part 2',
        review: 'Ôn lại lesson 9 (Vocab: chủ đề Airlines và Trains)',
      },
      {
        day: 'Day 18',
        newLesson: 'Lesson 7: Ordering lunch và Cooking as a career',
        review: 'Ôn lại Lesson 1 (Khóa từ vựng)',
      },
      { day: 'Day 19', newLesson: 'Lesson 10: Reading part 7-Paraphrasing', review: 'Ôn lại lesson 10 (Khóa từ vựng)' },
      { day: 'Day 20', newLesson: 'Lesson 8: Events và General travel', review: 'Ôn lại Lesson 2 (Khóa từ vựng)' },
      {
        day: 'Day 21',
        newLesson: 'Lesson 11: Reading Part 6 và 7 - Câu hỏi diễn câu vào đoạn văn',
        review: 'Ôn lại Lesson 7 (Khóa từ vựng)',
      },
      { day: 'Day 22', newLesson: 'Lesson 9: Airlines và Trains', review: 'Ôn lại Lesson 3 (Khóa từ vựng)' },
      { day: 'Day 23', newLesson: 'Lesson 12: Listening Part 3 - Câu hỏi về bảng biểu', review: null },
      {
        day: 'Day 24',
        newLesson: 'Lesson 10: Hotels và Car rentals',
        review: 'Ôn lại lesson 9 (Vocab: chủ đề Airlines và Trains)',
      },
      {
        day: 'Day 25',
        newLesson: 'Lesson 13: Part 5 - Mệnh đề quan hệ nâng cao',
        review: 'Ôn lại lesson 2 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 26', newLesson: 'Mini test 2 (Khóa TOEIC 600-800+)', review: 'Ôn lại lesson 10 (Khóa từ vựng)' },
      {
        day: 'Day 27',
        newLesson: 'Kiểm tra giữa kì (Khóa TOEIC 600-800+)',
        review: 'Ôn lại lesson 3 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 28', newLesson: 'Lesson 11: Movies và Theater', review: 'Ôn lại Lesson 7 (Khóa từ vựng)' },
      {
        day: 'Day 29',
        newLesson: 'Lesson 14: Listening Part 4 - Dạng câu hỏi chi tiết',
        review: 'Ôn lại lesson 4 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 30', newLesson: 'Lesson 12: Music và Museums', review: 'Ôn lại lesson Lesson 8 (Khóa từ vựng)' },
      {
        day: 'Day 31',
        newLesson: 'Lesson 15: Reading Part 5 và 6 - Mệnh đề quan hệ rút gọn',
        review: 'Ôn lại lesson 5 + 6 (Khóa TOEIC 600-800+)',
      },
      {
        day: 'Day 32',
        newLesson: "Lesson 13: Media và Doctor's office",
        review: 'Ôn lại Lesson 1 và 9 (Khóa từ vựng)',
      },
      {
        day: 'Day 33',
        newLesson: 'Lesson 16: Part 2-4 bẫy phổ biến của bài thi',
        review: 'Ôn lại lesson 7 (Khóa TOEIC 600-800+)',
      },
      {
        day: 'Day 34',
        newLesson: "Lesson 14: Dentist's office và Health insurance",
        review: 'Xem lại Minitest 1; Ôn lại Lesson 2 và 3 (Khóa từ vựng)',
      },
      {
        day: 'Day 35',
        newLesson: 'Lesson 17: Listening Part 3-3 bẫy phổ biến của bài thi',
        review: 'Ôn lại Lesson 8 + 9 (Khóa TOEIC 600-800+)',
      },
      {
        day: 'Day 36',
        newLesson: 'Lesson 15: Hospitals và Pharmacy',
        review: 'Ôn lại lesson 4, 5, 11 và 12; Xem lại Minitest 1 (Khóa từ vựng)',
      },
      {
        day: 'Day 37',
        newLesson: 'Lesson 18: Reading Part 5 và 6 - Thể giả định theo sau là dộng từ số ít + hòa hợp chủ vị nâng cao',
        review: 'Ôn lại Lesson 10 (Khóa TOEIC 600-800+)',
      },
      {
        day: 'Day 38',
        newLesson: 'Mini test 3 (Khóa TOEIC 600-800+)',
        review: 'Ôn lại Lesson 6, 7 và 13 (Khóa từ vựng)',
      },
      {
        day: 'Day 39',
        newLesson: 'Lesson 19: Part 4 - Cách xử lí câu hỏi cuối cùng của bài nghe Part 4',
        review: 'Ôn lại Lesson 11 + 12 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 40', newLesson: null, review: 'Ôn lại lesson 14 và 15 (Khóa từ vựng)' },
      {
        day: 'Day 41',
        newLesson: 'Lesson 20: Reading part 6 - Câu hỏi từ vựng',
        review: 'Lesson 13 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 42', newLesson: null, review: 'Xem lại Minitest 2; Ôn lại Lesson 8, 9 và 10 (Khóa từ vựng)' },
      {
        day: 'Day 43',
        newLesson: 'Lesson 21-Reading Part 7-Kĩ năng Skimming và Scanning',
        review: 'Lesson 14 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 44', newLesson: null, review: 'Ôn lại Lesson 11 và 12 (Khóa từ vựng)' },
      {
        day: 'Day 45',
        newLesson: 'Lesson 22: Listening Part 4 - Bẫy Thông tin nhiễu',
        review: 'Lesson 15 + 16 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 46', newLesson: null, review: 'Xem lại Minitest 3; Ôn lại Lesson 13 và 14 (Khóa từ vựng)' },
      {
        day: 'Day 47',
        newLesson: 'Lesson 23: Ôn tập Reading Part 5 và 6',
        review: 'Lesson 2 và 17 (Khóa TOEIC 600-800+)',
      },
      {
        day: 'Day 48',
        newLesson: 'Lesson 24: Ôn tập Listening',
        review: 'Lesson 3, 4, 18 và 19 (Khóa TOEIC 600-800+)',
      },
      {
        day: 'Day 49',
        newLesson: 'Lesson 25: Ôn tập Reading Part 7+ Tổng ôn tập',
        review: 'Lesson 5, 6 và 20 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 50', newLesson: 'Kiểm tra cuối khóa', review: 'Lesson 7, 8, 21 và 22 (Khóa TOEIC 600-800+)' },
      {
        day: 'Day 51',
        newLesson: 'Chữa để Listening - Part 1',
        review: 'Lesson 9, 10, 11 và 23 (Khóa TOEIC 600-800+)',
      },
      { day: 'Day 52', newLesson: 'Chữa để Listening - Part 2', review: 'Lesson 12, 13 và 24 (Khóa TOEIC 600-800+)' },
      { day: 'Day 53', newLesson: 'Chữa để Listening - Part 3', review: 'Lesson 15, 16 và 25 (Khóa TOEIC 600-800+)' },
      {
        day: 'Day 54',
        newLesson: 'Chữa để Listening - Part 4; Mocktest 1 (New economy)',
        review: 'Ôn lại bài Lesson 17 và 18',
      },
      {
        day: 'Day 55',
        newLesson: 'Chữa để Reading - Part 5; Mocktest 2 (New economy)',
        review: 'Ôn lại bài lesson 19, 20 và 21',
      },
      {
        day: 'Day 56',
        newLesson: 'Chữa để Reading - Part 5; Mocktest 2 (New economy)',
        review: 'Ôn lại bài lesson 19, 20 và 21',
      },
      {
        day: 'Day 57',
        newLesson: 'Chữa để Reading - Part 6',
        review: 'Mocktest 3 (New economy); Ôn lại Lesson 22 và 23',
      },
      {
        day: 'Day 58',
        newLesson: 'Chữa để Reading - Part 7-A',
        review: 'Mocktest 4 (New economy); Ôn lại bài Lesson 24 và 25',
      },
      { day: 'Day 59', newLesson: 'Chữa để Reading - Part 7-B', review: 'Mocktest 5 (New economy)' },
      { day: 'Day 60', newLesson: 'NGHỈ NGƠI', review: null },
    ],
  },
}
